Michael
dustinsommerfeld/vs1lab pull request #6
Opened 2022-03-22 08:56 UTC by Michael5601

2022-03-22 11:54 UTC, dustinsommerfeld requested changes

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/index.html
> +                        <label id="discovery_search_label" for="discovery_search_input">Search term or keywords:</label><br>
We are not using `<br>`-Tags to break two elements. We design it in style.css file.

```suggestion
                        <label id="discovery_search_label" for="discovery_search_input">Search term or keywords:</label>
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +input[type = text] {
```suggestion
input[type=text] {
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +    border: 1px solid #000;
```suggestion
    border: 1px solid var(--border-color);
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +    border-color: lightgray;
```suggestion

```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +     border: 1px solid;
```suggestion
     border: 1px solid var(--border-color);
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +     border-color: gray;
```suggestion

```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +     color: gray;
```suggestion
     color: var(--gray-color);
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +    color: light-gray;
```suggestion
    color: var(--background-color);
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +     font: 1em/1.25em Arial, Helvetica, sans-serif;
The font is defined in `body`.

```suggestion

```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +     width: 150px;
Not necessary.

```suggestion

```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +    color: gray;
```suggestion
    color: var(--gray-color);
```

2022-03-22 11:54 UTC, dustinsommerfeld commented on Aufgabe1/gta_v1/public/stylesheets/style.css
> +    width: 150px;
Not necessary.

```suggestion

```

2022-03-22 18:13 UTC, dustinsommerfeld requested changes

2022-03-22 18:18 UTC, dustinsommerfeld approved these changes

2022-03-22 18:59 UTC, Lukas-sys approved these changes

2022-03-23 07:20 UTC, Cavi1012 reviewed
Good job Mr. Bangas

2022-03-23 07:21 UTC, Cavi1012 approved these changes

2022-03-23 09:07 UTC, merged